### ISSUE TITLE
Template Validation Error

### ISSUE THREAD

**Issue by Pataraphol** [aws-quickstart/quickstart-bitnami-wordpress#12]
getting this error when run
"Template validation error: Template format error: Unresolved resource dependencies [ConfigureSSLStack] in the Resources block of the template"
Template URL = https://aws-quickstart.s3.amazonaws.com/quickstart-bitnami-wordpress/templates/wordpress-master.template
Thank you

**Comment by adriansecretsource** [comment]
Same problem over here when not specifying a DomainName creating the stack. Any luck with that?

**Comment by agamzn** [comment]
Working on this. Apologies for the delay.

**Comment by agamzn** [comment]
Hey @adriansecretsource , I've just pushed a commit to develop that should address this. It'll be a bit before everything flushed out to S3. (CI testing on our side).

**Comment by agamzn** [comment]
This also resolves #11

**Comment by agamzn** [comment]
Follow up: Our Ci/CD pipeline normally iterates within a few hours; We had an upstream bug that prevented the run from "succeeding". 

https://github.com/aws-quickstart/taskcat/issues/168

This commit passed but the deep cleanup failed, so the job failed. The fix has been pushed into the taskcat codebase.  I'm re-running the job now.

**Comment by Pataraphol** [comment]
adriansecretsource  For me, I didn't specify or use SSL (not for production use).   So, I was able to get over it and ran stack successfully by modifying wordpress-master.template.  I remove the line "Condition":"UseSSL", in the section below:  If you specify SSL and still get error, it might be a different issue.
---------------------------------------------------------------
"ConfigureSSLStack": {

			      "DependsOn":"CopyLambdaStack",

            "Condition":"UseSSL",
