### ISSUE TITLE
Add .htaccess file

### ISSUE THREAD

**Issue by adriansecretsource** [aws-quickstart/quickstart-bitnami-wordpress#16]
Currently there is not any .htaccess file in the AMI. When one is created, it's created just in one instance and it get lost in the auto scaling processes. 

I would suggest to add a .htaccess file to the EFS and map it in the WordPress directory as it's done with wp-content folder. So it can be available in all the instances with any changes made for the sysadmins.

**Comment by adriansecretsource** [comment]
Haven't think on that before! Thanks @beltran-rubo I'll give it a try.

**Comment by agamzn** [comment]
@adriansecretsource  - circling back on this. Did Beltran's suggestion address your concern?

**Comment by adriansecretsource** [comment]
Yes, you can marked it as solved. :+1:

**Comment by gmansilla** [comment]
> I would suggest a different approach. You can modify the "/bitnami/apache/conf/vhosts/wordpress-vhost.conf" that is already in EFS and you can add the htaccess rules into the section. That way will be available for all the nodes.

My installation only has 2 directories under /bitnami: /varnish and /wordpress.

Where would I add new settings? like enabling apache module remoteip?

Thanks.

**Comment by taofik-nos** [comment]
@gmansilla I believe it's under the  /opt/bitnami/apache/conf/vhosts
