### ISSUE TITLE
Add listener on port 80 of load balancer such that rewriting http to https works

### ISSUE THREAD

**Issue by fletling** [aws-quickstart/quickstart-bitnami-wordpress#18]
When configuring the quickstart template with an SSL certificate, I would expect it to rewrite any http request to https (Please let me know if it's a conscious decision to *not* do this). 

The security groups are already configured to allow inbound traffic on port 80 as well as 443, also the apache is configured to rewrite http to https. So far everything makes sense. 

However there's one piece missing: 
The load balancer only get's a listener on port 443. It needs to get another one on port 80. Otherwise all http requests result in `Connection refused`

**Comment by agamzn** [comment]
Thanks for the heads up; It's not an intentional omission; a PR to address this is coming shortly.

**Comment by agamzn** [comment]
@andresbono  - Is this something your team has a little bandwidth to throw at? I anticipated being able to circle back on this by now. :/

**Comment by andresbono** [comment]
@agamzn, yes, we'll take a look at it. Reassign the issue if you want 👍 

@fletling, expect an update of the progress during the next week!

**Comment by juan131** [comment]
Hi @fletling 

I did a PR to address the issue and it was already landed into the 'develop' branch. Could you give it a try? It should create two listeners, where the one listening at port 80 redirects all the traffic to port 443 over HTTPS.

When do we expect to have these changes landed in 'master' @agamzn ?

**Comment by agamzn** [comment]
@juan131  - Within the next hour or so. Our CI/CD pipeline is chewing on it now.

**Comment by agamzn** [comment]
@juan131 , @fletling  - this is now in master. I'm going to close this issue; please reopen if needed.

**Comment by fletling** [comment]
@andrew-glenn I just now had the chance to give this a try - works nicely. Thanks for the fix! 👍
