### ISSUE TITLE
Add trailing slash in default value for "QSS3KeyPrefix"

### ISSUE THREAD

**Issue by adionditsak** [aws-quickstart/quickstart-bitnami-wordpress#26]
Add trailing slash in default value for `"QSS3KeyPrefix": { ... "Default": "quickstart-bitnami-wordpress/"`. In both wordpress.template and webserver.template. Otherwise creation will fail, or you would have to make your own repository in s3. The default is nice to have tho.

**Comment by andresbono** [comment]
Hi @adionditsak, thanks for submitting the issue.

We are going to check what we can do to improve it and standardize the default values.

**Comment by agamzn** [comment]
@adionditsak @andresbono  - I've addressed this.
