### ISSUE TITLE
Recommended EFS Throughput mode to Provisioned rather than General

### ISSUE THREAD

**Issue by adionditsak** [aws-quickstart/quickstart-bitnami-wordpress#27]
Is there a reason the general throughput mode for EFS is set to General for this quickstart and not Provisioned?

https://docs.aws.amazon.com/efs/latest/ug/performance.html#throughput-modes

`Provisioned Throughput mode is available for applications with high throughput to storage (MiB/s per TiB) ratios, or with requirements greater than those allowed by the Bursting Throughput mode. For example, say you're using Amazon EFS for development tools, web serving, or content management applications where the amount of data in your file system is low relative to throughput demands. Your file system can now get the high levels of throughput your applications require without having to pad your file system.`

**Comment by rafariossaa** [comment]
Hi @adionditsak,
  We are using General as it is the recommended for web servers, as stated here: https://docs.aws.amazon.com/efs/latest/ug/performance.html#generalpurpose , but anyway we have in our backlog to do some benchmarks to detect bottlenecks and try to increase performance.

**Comment by rafariossaa** [comment]
Hi @adionditsak ,
  Could you check my answer in the related issue:

https://github.com/aws-quickstart/quickstart-bitnami-wordpress/issues/21

Best regards,
Rafael Rios Saavedra
