### ISSUE TITLE
Allow use of t3 instances for all services

### ISSUE THREAD

**Issue by Erowlin** [aws-quickstart/quickstart-bitnami-wordpress#35]
Hello, 

thank you for providing this template! 

I was wondering why the EC2 t3.* instances are not available for the following resources:
- `DBInstanceClass` (Databases) https://aws.amazon.com/rds/aurora/pricing/
- `BastionInstanceType` (The hosts to access the private subnets) https://aws.amazon.com/ec2/pricing/

The t3 are more cost effective solutions than t2. I understand for the ElasticCache that you don't list t2, because they simply does not exists yet :).

Also, and this is a more general question, NGinx is a blast as a web server, why did you went with Apache? Do you plan to create a template that supports NGinx? 

Thank you.

**Comment by andresbono** [comment]
Hi @Erowlin,

>I was wondering why the EC2 t3.* instances are not available [...]

It makes sense, thanks for noticing. We will add that instance type family to the `AllowedValues`.

---

> Also, and this is a more general question, NGinx is a blast as a web server, why did you went with Apache? Do you plan to create a template that supports NGinx?

It is just that we have more experience configuring and optimizing Apache web servers :smile:. Creating a new set of images with NGINX is not in our short-term plans but I will register your suggestion.

**Comment by Erowlin** [comment]
Amazing, thank you. Can you add a comment here when it’s done? :)

**Comment by andrew-glenn** [comment]
@andresbono  - Y'all want me to take this on? It's pretty easy to knock out.

**Comment by andresbono** [comment]
@Erowlin, @andrew-glenn, I opened two PRs to fix this issue. Please take a look when you have a minute!

**Comment by Erowlin** [comment]
I've reviewed it. Just ping me in here whenever you have a chance to re-submit it.

**Comment by andrew-glenn** [comment]
Leaving open until both PRs iterate through our CI/CD pipeline. I expect we can close this later today.

**Comment by Erowlin** [comment]
Perfect thanks.

**Comment by andrew-glenn** [comment]
@andresbono @Erowlin - So... I jinxed myself by saying it'd be in master a week ago. Sorry about that. Nothing to do with this specific quickstart. We're sorted now. Enjoy!
