### ISSUE TITLE
Access Denied to S3 bucket for BastionStack

### ISSUE THREAD

**Issue by jtoporowski** [aws-quickstart/quickstart-bitnami-wordpress#51]
I launched this successfully a few months ago in the CA-Central-1 Region. Now when I try and do the same I get an error and roll back on the creation of the Bastion Host. I went to the bucket and the files appear to be there so I'm not sure what the issue is. 

I've tried this in multiple regions in multiple accounts today. EIP was not the issue, as I verified I had enough for the NAT Gateways and Bastion Host. 

The following resource(s) failed to create: [BastionStack]. . Rollback requested by user.
--
2020-08-08 16:00:06 UTC-0600 | BastionStack | CREATE_FAILED | S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by andrew-glenn** [comment]
@jtoporowski - this should now be resolved. apologies, we had a permissions hiccup on a couple of files in S3. Would you mind trying again?

**Comment by andrew-glenn** [comment]
I'm going to close this out for housekeeping purposes. Please reopen if this persists.
