### ISSUE TITLE
cache instance type mismatch

### ISSUE THREAD

**Issue by dukeluke16** [aws-quickstart/quickstart-bitnami-wordpress#55]
New VPC WordPress Template https://github.com/aws-quickstart/quickstart-bitnami-wordpress/blob/main/templates/wordpress-master.template#L737 has `cache.m3.medium`

Reuse VPC WordPress Template https://github.com/aws-quickstart/quickstart-bitnami-wordpress/blob/main/templates/wordpress.template#L658 has `cache.m3.medium`

ElastiCache Template https://github.com/aws-quickstart/quickstart-bitnami-wordpress/blob/main/templates/elasticache.template#L28 has `cache.t2.medium`

When selecting a cache instance node type for WordPress this does not match the underlying allowed value.  `cache.m3.medium` != `cache.t2.medium`

Work Around - select a size other than "medium"...

**Comment by andresbono** [comment]
Hi @dukeluke16, #56 fixes this issue. Thanks for reporting it!
