### ISSUE TITLE
Error deploying - syntax error in CleanUpS3BucketFunction

### ISSUE THREAD

**Issue by scottgerring** [aws-quickstart/quickstart-bitnami-wordpress#62]
I'm trying to launch this from the AWS Quickstart page, and am hitting a syntax error on the `CleanUpS3BucketFunction`:

```
[ERROR] Runtime.UserCodeSyntaxError: Syntax error in module 'index': Missing parentheses in call to 'print'. Did you mean print(CheckifVersioned)? (index.py, line 66)
Traceback (most recent call last):
  File "/var/task/index.py" Line 66
                print CheckifVersioned
```

from here:

https://github.com/aws-quickstart/quickstart-bitnami-wordpress/blob/28772077b4c2190a38fbc1a629cd877254b7f932/templates/copy-lambdas.template#L296-L299

As far as I know, `print 'bob'` doesn't work in Python3 - it needs to be a regular `print('bob')` function call invocation. Perhaps it was supported for a time and deprecated in the early days?

This issue is also present in `cfnresponse.py` and comes into play when deploying with an SSL certificate. I've raised a PR (linked) to address both of these.

**Comment by bmeiser** [comment]
Would this be what's causing this error in CloudFormation?
`Embedded stack arn:aws:cloudformation:us-east-2:069056413951:stack/CopyLambdaStack-1WL4Q7QPU0UMX/13158840-874a-11eb-9318-06994f12b84a was not successfully created: The following resource(s) failed to create: [CleanUpS3Bucket].`
