### ISSUE TITLE
S3 access denied on WordPress stack creation

### ISSUE THREAD

**Issue by wsummers77** [aws-quickstart/quickstart-bitnami-wordpress#79]
Tried in both us-east-2 and us-west-2. Deploying into a new VPC with all default configs each time. VPC and Bastion Stack create successfully but when it gets to the WordPress Stack it throws the following error and rolls back:

S3 error: Access Denied For more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html

**Comment by philippegabert** [comment]
Same error here. It used to work a few weeks ago.

**Comment by jftuga** [comment]
I am wondering if the removal of these 2 parameters could be the problem:

* https://github.com/aws-quickstart/quickstart-bitnami-wordpress/commit/d944e3e44ea0418e35c84f8a6dfd1e9f08106298#diff-9cd5fdeeb77b91f33c362e2380e29020900562218372ad0bca95953997c6da1dL85
* https://github.com/aws-quickstart/quickstart-bitnami-wordpress/commit/5aeaab6018c0c5a4cbfa6cadd641a87049c203c9#diff-7f14bb8caf9582aec0889ae994705bf44115abbbfbb15747213a51a65f103a13L923
*

**Comment by wsummers77** [comment]
This issue may be related.  https://github.com/aws-quickstart/quickstart-bitnami-wordpress/issues/76#issue-1074784537

**Comment by wsummers77** [comment]
Output from: $aws cloudformation describe-stack-events --stack-name WordPress-HA-by-Bitnami

          {
              "StackId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "EventId": "4ed551b0-7945-11ec-b5dd-06a7646ae00c",
              "StackName": "WordPress-HA-by-Bitnami",
              "LogicalResourceId": "WordPress-HA-by-Bitnami",
              "PhysicalResourceId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "ResourceType": "AWS::CloudFormation::Stack",
              "Timestamp": "2022-01-19T16:31:52.264000+00:00",
              "ResourceStatus": "CREATE_FAILED",
              "ResourceStatusReason": "The following resource(s) failed to create: [WordPressStack]. ",
              "ClientRequestToken": "Console-CreateStack-da814bb7-a4f3-a7b2-2100-7c535513ef33"
          },
          {
              "StackId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "EventId": "WordPressStack-CREATE_FAILED-2022-01-19T16:31:51.033Z",
              "StackName": "WordPress-HA-by-Bitnami",
              "LogicalResourceId": "WordPressStack",
              "PhysicalResourceId": "",
              "ResourceType": "AWS::CloudFormation::Stack",
              "Timestamp": "2022-01-19T16:31:51.033000+00:00",
              "ResourceStatus": "CREATE_FAILED",
              "ResourceStatusReason": "S3 error: Access Denied\nFor more information check http://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html",
              "ResourceProperties": "{\"TemplateURL\":\"https://aws-quickstart-us-east-2.s3.us-east-2.amazonaws.com/quickstart-bitnami-wordpress/templates/wordpress.template\",\"Parameters\":{\"ALBAccessCIDR\":\"0.0.0.0/0\",\"WebServerInstanceType\":\"t3.small\",\"WebServerAMI\":\"\",\"VPCID\":\"vpc-0488129ea8e1c3b53\",\"HostedZoneID\":\"\",\"QSS3KeyPrefix\":\"quickstart-bitnami-wordpress/\",\"BastionSecurityGroupID\":\"sg-0c9333519bb99f2c0\",\"AutoScalingNotificationEmail\":\"xxxxxxx@email.email\",\"DBAutoMinorVersionUpgrade\":\"true\",\"DBPreferredBackupWindow\":\"\",\"WebServerInstanceMonitoring\":\"Enabled\",\"DBStorageEncrypted\":\"false\",\"DBBackupRetentionPeriod\":\"7\",\"ElastiCacheAutoMinorVersionUpgrade\":\"true\",\"ElastiCacheEnable\":\"false\",\"VPCCIDR\":\"10.0.0.0/16\",\"ElastiCacheNodeType\":\"cache.t3.medium\",\"DBMultiAZ\":\"false\",\"KeyPairName\":\"sa-ohio-dev-keypair\",\"QSS3BucketName\":\"aws-quickstart\",\"DBInstanceClass\":\"db.t2.small\",\"DBMasterUserPassword\":\"****\",\"DomainName\":\"\",\"WebServerMinSize\":\"1\",\"PrivateSubnet2ID\":\"subnet-011476524770af0b8\",\"PrivateSubnet1ID\":\"subnet-0741998c20a41de99\",\"WebServerDesiredCapacity\":\"1\",\"PublicSubnet1ID\":\"subnet-0a5d2c7e659460f6f\",\"PublicSubnet2ID\":\"subnet-068d5d0062fac549a\",\"WebServerMaxSize\":\"2\",\"QSS3BucketRegion\":\"us-east-1\",\"WordpressAdminPassword\":\"****\",\"ElastiCacheNumberOfNodes\":\"2\"}}",
              "ClientRequestToken": "Console-CreateStack-da814bb7-a4f3-a7b2-2100-7c535513ef33"
          },
          {
              "StackId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "EventId": "WordPressStack-CREATE_IN_PROGRESS-2022-01-19T16:31:50.354Z",
              "StackName": "WordPress-HA-by-Bitnami",
              "LogicalResourceId": "WordPressStack",
              "PhysicalResourceId": "",
              "ResourceType": "AWS::CloudFormation::Stack",
              "Timestamp": "2022-01-19T16:31:50.354000+00:00",
              "ResourceStatus": "CREATE_IN_PROGRESS",
              "ResourceProperties": "{\"TemplateURL\":\"https://aws-quickstart-us-east-2.s3.us-east-2.amazonaws.com/quickstart-bitnami-wordpress/templates/wordpress.template\",\"Parameters\":{\"ALBAccessCIDR\":\"0.0.0.0/0\",\"WebServerInstanceType\":\"t3.small\",\"WebServerAMI\":\"\",\"VPCID\":\"vpc-0488129ea8e1c3b53\",\"HostedZoneID\":\"\",\"QSS3KeyPrefix\":\"quickstart-bitnami-wordpress/\",\"BastionSecurityGroupID\":\"sg-0c9333519bb99f2c0\",\"AutoScalingNotificationEmail\":\"xxxxxxx@email.email\",\"DBAutoMinorVersionUpgrade\":\"true\",\"DBPreferredBackupWindow\":\"\",\"WebServerInstanceMonitoring\":\"Enabled\",\"DBStorageEncrypted\":\"false\",\"DBBackupRetentionPeriod\":\"7\",\"ElastiCacheAutoMinorVersionUpgrade\":\"true\",\"ElastiCacheEnable\":\"false\",\"VPCCIDR\":\"10.0.0.0/16\",\"ElastiCacheNodeType\":\"cache.t3.medium\",\"DBMultiAZ\":\"false\",\"KeyPairName\":\"sa-ohio-dev-keypair\",\"QSS3BucketName\":\"aws-quickstart\",\"DBInstanceClass\":\"db.t2.small\",\"DBMasterUserPassword\":\"****\",\"DomainName\":\"\",\"WebServerMinSize\":\"1\",\"PrivateSubnet2ID\":\"subnet-011476524770af0b8\",\"PrivateSubnet1ID\":\"subnet-0741998c20a41de99\",\"WebServerDesiredCapacity\":\"1\",\"PublicSubnet1ID\":\"subnet-0a5d2c7e659460f6f\",\"PublicSubnet2ID\":\"subnet-068d5d0062fac549a\",\"WebServerMaxSize\":\"2\",\"QSS3BucketRegion\":\"us-east-1\",\"WordpressAdminPassword\":\"****\",\"ElastiCacheNumberOfNodes\":\"2\"}}",
              "ClientRequestToken": "Console-CreateStack-da814bb7-a4f3-a7b2-2100-7c535513ef33"
          },
          {
              "StackId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "EventId": "BastionStack-CREATE_COMPLETE-2022-01-19T16:31:47.254Z",
              "StackName": "WordPress-HA-by-Bitnami",
              "LogicalResourceId": "BastionStack",
              "PhysicalResourceId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami-BastionStack-1BD78IIWOIA95/774d62a0-7944-11ec-89e8-0a4d7a11b74c",
              "ResourceType": "AWS::CloudFormation::Stack",
              "Timestamp": "2022-01-19T16:31:47.254000+00:00",
              "ResourceStatus": "CREATE_COMPLETE",
              "ResourceProperties": "{\"TemplateURL\":\"https://aws-quickstart-us-east-2.s3.us-east-2.amazonaws.com/quickstart-bitnami-wordpress/submodules/quickstart-linux-bastion/templates/linux-bastion.template\",\"Parameters\":{\"KeyPairName\":\"sa-ohio-dev-keypair\",\"QSS3BucketName\":\"aws-quickstart\",\"BastionInstanceType\":\"t2.micro\",\"PublicSubnet1ID\":\"subnet-0a5d2c7e659460f6f\",\"PublicSubnet2ID\":\"subnet-068d5d0062fac549a\",\"VPCID\":\"vpc-0488129ea8e1c3b53\",\"RemoteAccessCIDR\":\"0.0.0.0/0\",\"QSS3BucketRegion\":\"us-east-1\",\"BastionAMIOS\":\"Amazon-Linux2-HVM\",\"QSS3KeyPrefix\":\"quickstart-bitnami-wordpress/submodules/quickstart-linux-bastion/\"}}",
              "ClientRequestToken": "Console-CreateStack-da814bb7-a4f3-a7b2-2100-7c535513ef33"
          },
          {
              "StackId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "EventId": "BastionStack-CREATE_IN_PROGRESS-2022-01-19T16:25:51.106Z",
              "StackName": "WordPress-HA-by-Bitnami",
              "LogicalResourceId": "BastionStack",
              "PhysicalResourceId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami-BastionStack-1BD78IIWOIA95/774d62a0-7944-11ec-89e8-0a4d7a11b74c",
              "ResourceType": "AWS::CloudFormation::Stack",
              "Timestamp": "2022-01-19T16:25:51.106000+00:00",
              "ResourceStatus": "CREATE_IN_PROGRESS",
              "ResourceStatusReason": "Resource creation Initiated",
              "ResourceProperties": "{\"TemplateURL\":\"https://aws-quickstart-us-east-2.s3.us-east-2.amazonaws.com/quickstart-bitnami-wordpress/submodules/quickstart-linux-bastion/templates/linux-bastion.template\",\"Parameters\":{\"KeyPairName\":\"sa-ohio-dev-keypair\",\"QSS3BucketName\":\"aws-quickstart\",\"BastionInstanceType\":\"t2.micro\",\"PublicSubnet1ID\":\"subnet-0a5d2c7e659460f6f\",\"PublicSubnet2ID\":\"subnet-068d5d0062fac549a\",\"VPCID\":\"vpc-0488129ea8e1c3b53\",\"RemoteAccessCIDR\":\"0.0.0.0/0\",\"QSS3BucketRegion\":\"us-east-1\",\"BastionAMIOS\":\"Amazon-Linux2-HVM\",\"QSS3KeyPrefix\":\"quickstart-bitnami-wordpress/submodules/quickstart-linux-bastion/\"}}",
              "ClientRequestToken": "Console-CreateStack-da814bb7-a4f3-a7b2-2100-7c535513ef33"
          },
          {
              "StackId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "EventId": "BastionStack-CREATE_IN_PROGRESS-2022-01-19T16:25:50.288Z",
              "StackName": "WordPress-HA-by-Bitnami",
              "LogicalResourceId": "BastionStack",
              "PhysicalResourceId": "",
              "ResourceType": "AWS::CloudFormation::Stack",
              "Timestamp": "2022-01-19T16:25:50.288000+00:00",
              "ResourceStatus": "CREATE_IN_PROGRESS",
              "ResourceProperties": "{\"TemplateURL\":\"https://aws-quickstart-us-east-2.s3.us-east-2.amazonaws.com/quickstart-bitnami-wordpress/submodules/quickstart-linux-bastion/templates/linux-bastion.template\",\"Parameters\":{\"KeyPairName\":\"sa-ohio-dev-keypair\",\"QSS3BucketName\":\"aws-quickstart\",\"BastionInstanceType\":\"t2.micro\",\"PublicSubnet1ID\":\"subnet-0a5d2c7e659460f6f\",\"PublicSubnet2ID\":\"subnet-068d5d0062fac549a\",\"VPCID\":\"vpc-0488129ea8e1c3b53\",\"RemoteAccessCIDR\":\"0.0.0.0/0\",\"QSS3BucketRegion\":\"us-east-1\",\"BastionAMIOS\":\"Amazon-Linux2-HVM\",\"QSS3KeyPrefix\":\"quickstart-bitnami-wordpress/submodules/quickstart-linux-bastion/\"}}",
              "ClientRequestToken": "Console-CreateStack-da814bb7-a4f3-a7b2-2100-7c535513ef33"
          },
          {
              "StackId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "EventId": "VPCStack-CREATE_COMPLETE-2022-01-19T16:25:47.457Z",
              "StackName": "WordPress-HA-by-Bitnami",
              "LogicalResourceId": "VPCStack",
              "PhysicalResourceId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami-VPCStack-10Y1ZGZVU37D7/f71067e0-7943-11ec-98ea-02a08ac43f20",
              "ResourceType": "AWS::CloudFormation::Stack",
              "Timestamp": "2022-01-19T16:25:47.457000+00:00",
              "ResourceStatus": "CREATE_COMPLETE",
              "ResourceProperties": "{\"TemplateURL\":\"https://aws-quickstart-us-east-2.s3.us-east-2.amazonaws.com/quickstart-bitnami-wordpress/submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml\",\"Parameters\":{\"PublicSubnet2CIDR\":\"10.0.144.0/20\",\"AvailabilityZones\":\"us-east-2a,us-east-2b\",\"NumberOfAZs\":\"2\",\"VPCCIDR\":\"10.0.0.0/16\",\"PrivateSubnet2ACIDR\":\"10.0.32.0/19\",\"PrivateSubnet1ACIDR\":\"10.0.0.0/19\",\"PublicSubnet1CIDR\":\"10.0.128.0/20\"}}",
              "ClientRequestToken": "Console-CreateStack-da814bb7-a4f3-a7b2-2100-7c535513ef33"
          },
          {
              "StackId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "EventId": "VPCStack-CREATE_IN_PROGRESS-2022-01-19T16:22:16.003Z",
              "StackName": "WordPress-HA-by-Bitnami",
              "LogicalResourceId": "VPCStack",
              "PhysicalResourceId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami-VPCStack-10Y1ZGZVU37D7/f71067e0-7943-11ec-98ea-02a08ac43f20",
              "ResourceType": "AWS::CloudFormation::Stack",
              "Timestamp": "2022-01-19T16:22:16.003000+00:00",
              "ResourceStatus": "CREATE_IN_PROGRESS",
              "ResourceStatusReason": "Resource creation Initiated",
              "ResourceProperties": "{\"TemplateURL\":\"https://aws-quickstart-us-east-2.s3.us-east-2.amazonaws.com/quickstart-bitnami-wordpress/submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml\",\"Parameters\":{\"PublicSubnet2CIDR\":\"10.0.144.0/20\",\"AvailabilityZones\":\"us-east-2a,us-east-2b\",\"NumberOfAZs\":\"2\",\"VPCCIDR\":\"10.0.0.0/16\",\"PrivateSubnet2ACIDR\":\"10.0.32.0/19\",\"PrivateSubnet1ACIDR\":\"10.0.0.0/19\",\"PublicSubnet1CIDR\":\"10.0.128.0/20\"}}",
              "ClientRequestToken": "Console-CreateStack-da814bb7-a4f3-a7b2-2100-7c535513ef33"
          },
          {
              "StackId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "EventId": "VPCStack-CREATE_IN_PROGRESS-2022-01-19T16:22:15.199Z",
              "StackName": "WordPress-HA-by-Bitnami",
              "LogicalResourceId": "VPCStack",
              "PhysicalResourceId": "",
              "ResourceType": "AWS::CloudFormation::Stack",
              "Timestamp": "2022-01-19T16:22:15.199000+00:00",
              "ResourceStatus": "CREATE_IN_PROGRESS",
              "ResourceProperties": "{\"TemplateURL\":\"https://aws-quickstart-us-east-2.s3.us-east-2.amazonaws.com/quickstart-bitnami-wordpress/submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml\",\"Parameters\":{\"PublicSubnet2CIDR\":\"10.0.144.0/20\",\"AvailabilityZones\":\"us-east-2a,us-east-2b\",\"NumberOfAZs\":\"2\",\"VPCCIDR\":\"10.0.0.0/16\",\"PrivateSubnet2ACIDR\":\"10.0.32.0/19\",\"PrivateSubnet1ACIDR\":\"10.0.0.0/19\",\"PublicSubnet1CIDR\":\"10.0.128.0/20\"}}",
              "ClientRequestToken": "Console-CreateStack-da814bb7-a4f3-a7b2-2100-7c535513ef33"
          },
          {
              "StackId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "EventId": "f36699c0-7943-11ec-9f7a-061b0c7bef22",
              "StackName": "WordPress-HA-by-Bitnami",
              "LogicalResourceId": "WordPress-HA-by-Bitnami",
              "PhysicalResourceId": "arn:aws:cloudformation:us-east-2:123456789:stack/WordPress-HA-by-Bitnami/f3649df0-7943-11ec-9f7a-061b0c7bef22",
              "ResourceType": "AWS::CloudFormation::Stack",
              "Timestamp": "2022-01-19T16:22:09.763000+00:00",
              "ResourceStatus": "CREATE_IN_PROGRESS",
              "ResourceStatusReason": "User Initiated",
              "ClientRequestToken": "Console-CreateStack-da814bb7-a4f3-a7b2-2100-7c535513ef33"
          }
      ]
    }

**Comment by andrew-glenn** [comment]
This was a transient error that's now resolved. Apologies for the inconvenience.

**Comment by GregFIHB** [comment]
This is is happening for me currently.
